### ISSUE TITLE
[1.12.2] Furnaces can only smelt one item at once

### ISSUE THREAD

**Issue by Shahelion** [Shadows-of-Fire/FastFurnace#44]
If there is anything in the output slot, it can't smelt any more until that item is removed.

Unlike everyone else with this issue, I do not have the CustomNPCs mod, so something else is causing this.

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported, you'll have to figure that one out on your own.

**Comment by CosmicHikari** [comment]
I do use the customNPCs mod and this issue is presented. I will be uninstalling fastfurnace now knowing that "1.12 is not supported". This is clearly a forge data tag issue with fastfurnace and can not be fixed by customnpcs (as said by Noppes himself).

OP: If you want normal functionality of the furnace, remove fast furnace, otherwise remove mods one at a time until you find the incompatible mod.
